#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countApplesAndOranges' function below.
#
# The function accepts following parameters:
#  1. INTEGER s
#  2. INTEGER t
#  3. INTEGER a
#  4. INTEGER b
#  5. INTEGER_ARRAY apples
#  6. INTEGER_ARRAY oranges
#

def countApplesAndOranges(s, t, a, b, apples, oranges):
    # Write your code here
    a_count=0
    b_count=0
    for i in apples:
        if(a+i>=s and a+i<=t):
            a_count=a_count+1
    for j in oranges:
        if(b+j>=s and b+j<=t):
            b_count=b_count+1
    print(a_count)
    print(b_count)
    
    
if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    # range
    s = int(first_multiple_input[0]) 

    t = int(first_multiple_input[1])

    second_multiple_input = input().rstrip().split()

    # position of tree
    a = int(second_multiple_input[0])

    b = int(second_multiple_input[1])

    third_multiple_input = input().rstrip().split()

    # m=no. of apple n=no. of oranges
    m = int(third_multiple_input[0])

    n = int(third_multiple_input[1])

    # where fruits fall
    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
