#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'compareTriplets' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#

def compareTriplets(a, b):
    # Write your code here
    Alc = 0
    bob = 0
    for i in range(len(a)):
        if a[i] > b[i]:
            Alc = Alc + 1
            print('alc',Alc)
        elif a[i] < b[i]:
            bob = bob + 1
            print('b',bob)
        elif a[i] == b[i]:
            Alc = Alc + 0
            bob = bob + 0
    return [Alc, bob]
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
