#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    arr.sort()
    f_sum=0
    s_sum=0
    # Write your code here
    for i in range(0,len(arr)-1):
        f_sum=f_sum+arr[i]
    for j in range(1,len(arr)):
        s_sum=s_sum+arr[j]
    print(f_sum, s_sum)

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
